apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-jenkins-app
spec:
  selector:
    matchLabels:
      app: learn-jenkins-app
  template:
    metadata:
      labels:
        app: learn-jenkins-app
    spec:
      containers:
      - name: learn-jenkins-app
        image: thanhtha/learn-jenkins-app:1.0.0-27
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
